### ISSUE TITLE
Items not generating correctly

### ISSUE THREAD

**Issue by heyitsaximo** [arcadiadevs/gensplus-issues#47]
**Describe the bug**
When holograms are enabled and when the same generators are clustered up, it will just generate one item

**To Reproduce**
1. Enable Holograms in config
2. Place the same generators in one spot
3. The generators will only produce one item if they are sharing the same hologram

**Config**
```
particles:
  # If enabled is set to false, particles will not be displayed upon upgrade.
  enabled: true
  
  # Type of the particle. Make sure to use particles
  # that are supported by your server version, otherwise,
  # the particles will not be displayed. You can find
  # all supported particles here:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  type: FIREWORKS_SPARK
  
  # Sound that will be played upon upgrade.
  # You can find all supported sounds here:
  # https://github.com/dieterblancke/DonatorJoinPlus/blob/master/spigot/src/main/java/com/dbsoftwares/djp/spigot/utils/XSound.java
  sound: ENTITY_GENERIC_EXPLODE

# If lore is not specified, the default lore will be used.
# The default lore can be specified in the following format:
# - %tier%" equals to the generator's tier
# - %speed%" is the generator's speed of spawning items
# - %price%" is the price of generator
# - %sellPrice%" is the sell price of generator drop
# - %spawnItem%" equals to what item will generator spawn
# - %blockType%" equals to block type of generator
default-lore:
- '&7Place down to start generating items!'
- ''
- '&e&l⌈ &6Tier: &7%tier%'
- '&e&lⅠ &6Speed: &7%speed%'
- '&e&lⅠ &6Price: &a%price%'
- '&e&l⌊ &6Sell Price: &a%sellPrice%'
- ''
- '&e&l⌈ &6Spawn Item: &7%spawnItem%'
- '&e&l⌊ &6Block Type: &7%blockType%'

# If itemSpawnLore is not specified, the default item spawn lore will be used.
# The default item spawn lore can be specified in the following format:
# - %sellPrice%" is the sell price of the generator drop
default-item-spawn-lore:
- '&7Type in chat &e/selldrops &6hand&8/&6all'
- '&7to sell the drops for &e%sellPrice%'

# If hologramLines is not specified, the default hologram lines will be used.
# The default hologram lines can be specified in the following format:
# Lines that will be displayed above the generator
# Lines can be specified in the following format:
# %name% will be replaced with the name of the generator
# %tier% will be replaced with the tier of the generator
# %speed% will be replaced with the speed of the generator
# %spawnItem% will be replaced with the item that generator spawns
# %sellPrice% will be replaced with the sell price of the generator
default-hologram-lines:
- '&a%name%'
- '&7Tier: &a%tier%'
- '&7Spawns each &a%speed% &7seconds &a%spawnItem%'
- '&7Sells for &a%sellPrice%'

# generators represent the generators that will be added in the gui,
# name is the name of the generator
# tier is the tier of the generator (each generator must have a unique tier)
# price is the price of the generator
# sellPrice is the sell price of the generator drop
# speed is the speed of the generator (how often it will spawn items)
# spawnItem is the item that generator will spawn
# blockType is the block type of the generator
# lore is the lore of the generator (if not specified, the default lore will be used)
# itemSpawnLore is the lore of the generator drop (if not specified, the default item spawn lore will be used)
# hologramLines is the hologram lines of the generator (if not specified, the default hologram lines will be used)
# dropDisplayName is the display name of the generator drop
# instantBreak is whether the generator can be instantly broken by SHIT + RIGHT-clicking or not
generators:
HIDDEN
```

**Expected behavior**
If the generators are sharing one hologram, it should produce the same number of drops, depending on how many generators are sharing the same hologram.

**Screenshots**
![image](https://github.com/arcadiadevs/gensplus-issues/assets/82157643/0548277a-97b2-4538-ab78-b771e7978f80)

**Additional info (please complete the following information):**
 - GensPlus v.1.40.0
 - Paper 1.20.4
 - Using ViaVersion/ProtocolSupport [no]
 - Your MC version: 1.40.0

**Additional context**
-
